spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://ec2-44-205-64-253.compute-1.amazonaws.com:5432/df27kj78eckbbi
    username: ccqsjzfamhdgcw
    password: 8260a9e63e07b4f965db208d88cf963122f174f382b70ac23b291d06ece6fc47
    post: 5432
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_ssql: true
