spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-223-242-224.compute-1.amazonaws.com:5432/delhvg6g9k6loq
    username: bsxpakevnxwggp
    password: 474cf957475dc371a5d42c6036bf72869a6bc797acf36505245bf08f225d8816
jasypt:
  encryptor:
    bean: jasyptStringEncryptor